version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: projet_archi_users,projet_archi_reservations
    ports:
      - '5432:5432'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'

  users-service:
    build: ./users-service
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/projet_archi_users?schema=public
    depends_on:
      - db
      - rabbitmq

  reservations-service:
    build: ./reservations-service
    ports:
      - '8001:8001'
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/projet_archi_reservations?schema=public
      RABBITMQ_URL: amqp://rabbitmq:5672
      USER_SERVICE_API_URL: http://users-service:8000
    depends_on:
      - db
      - rabbitmq
